### PR TITLE
Add ContextKeyExprType to services

### PR DESCRIPTION
**Pull request by hunger**
I get errors about this type being absent, so I tried to fix this.

Please check this carefully, my typescript foo is still limited.

### CODE REVIEW

**Comment by hunger** [comment]
One of the errors I get:

```
5082     readonly type = ContextKeyExprType.GreaterEquals;
                         ~~~~~~~~~~~~~~~~~~

  node_modules/vscode/dist/services.d.ts:4998:15
    4998 declare class ContextKeyInExpr implements IContextKeyExpression {
                       ~~~~~~~~~~~~~~~~
    'ContextKeyInExpr' is declared here.
```

**Comment by CGNonofr** [comment]
You're right, it seems there is a bug in `rollup-plugin-dts` that doesn't realize `ContextKeyExprType` is used

**Comment by CGNonofr** [comment]
Thanks you for your contribution.

Unfortunately, your code doesn't build, and the issue exists in another module as well, so I created another PR "fixing" everything with some explanations

=> https://github.com/CodinGame/monaco-vscode-api/pull/42

**Comment by CGNonofr** [comment]
the v1.69.3 vas released, can you check?

**Comment by hunger** [comment]
Seems to work fine! Thanks!

**Pull request closed without merging**
