### PR TITLE
Small improvements

### LINKED ISSUE #193: Uninitialize or fully disable command palette and other global keybindings
Maybe I am completely missing something, but how do we correctly "uninitialize" vscode? This could be useful if you have a bigger website that only uses vscode/monaco in a specific area of the website. If you then browse away from this section it would be nice to properly unload vscode (think also performance/battery drain on laptops etc).

An alternative would be to fully disable quickaccess (command palette) without causing console warning (and possible any other keybindings???).
```typescript
await initialize({
        ...
        ...getQuickAccessServiceOverride({
          isKeybindingConfigurationVisible: () => false,
          shouldUseGlobalPicker: () => false, // <--- Illustrated for this issue, this will cause the warning if you have no editor instance in focus.
        }),
        ...
});
``` 
image

### PR DESCRIPTION
**Pull request by CGNonofr**
Based on https://github.com/CodinGame/monaco-vscode-api/pull/191

fix #193

also can help with #192 (waiting for extension to be loaded before trying to use it)

2 fix/features:
- Allow to disable to global keybinding service
- Allow to know when an extension is ready

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr will you release a next version of this?

**Comment by kaisalmen** [comment]
Strange, that was no issue locally (Linux) the other day when I updated.

**Comment by kaisalmen** [comment]
@CGNonofr if it saves time just downgrade to node 18.17.1 / npm 9.6.7 that was stable.

**Comment by CGNonofr** [comment]
I'm unable to publish the next version, for some reason, the publish hangs until I receive a 503 error after a few minutes, while I'm able to access/browse registry.npmjs.org :shrug: 

I'm trying for half an hour now...

**Comment by CGNonofr** [comment]
@kaisalmen ok it seems all my problems were due to a downtime of npmjs registry. It's fine now, published as 1.82.0-next.0

**Comment by kaisalmen** [comment]
@CGNonofr Superb. I will try it soon with `monaco-languageclient`

**Comment by CGNonofr** [comment]
@kaisalmen this PR contains ecverything, so maybe let's just approve and merge this one?

btw, there was an issue with the patch it seems. there was warning while applying it, I've updated it: 68db6dd97c6c9e67b1c4e1b8da6e80cbd74d7d53

also, and I don't really know the cause, but webview were not working since the update, because of vite being dumb once again, trying to heavily transform html assets this time, thinking it was the index.html file, injecting its monitoring script, replacing inline script by external script... breaking everything => 11f713ae38cd07bcdd385db2241205f65ca90fba to just serve html file as is in dev mode (there is no issue in build mode)

**Review by kaisalmen — APPROVED** [review]
LGTM. The whole PR stack (this +#184 and #191) is working with the next version of `monaco-languageclient`.

Let's get this all in and iterate from there. One thing I don't like is that the vite config for (in demo here, but also in `monaco-languageclient`) needs this all these extra configs and experimental node features. We should improve the end-user experience if possible. Bundling with rollup and webpack is fine.

**Comment by kaisalmen** [comment]
> btw, there was an issue with the patch it seems. there was warning while applying it,

Saw that. Thank you.

> this PR contains ecverything, so maybe let's just approve and merge this one?

Yes, let's do this.

> because of vite being dumb once again

I was writing my approval comment when your comment came in. Let's discuss potential vite improvements in a new issue. WDYT?

**Comment by CGNonofr** [comment]
> Let's get this all in and iterate from there. One thing I don't like is that the vite config for (in demo here, but also in `monaco-languageclient`) needs this all these extra configs and experimental node features. We should improve the end-user experience if possible. Bundling with rollup and webpack is fine.

I agree. Vite was promising but it's very complex and they implemented a lot of behaviors. That's really hard to understand their code, there is a lot of plugins. I'm trying to fix our issues on their side but there is no reaction...

All issues are related to asset management in node_modules in dev mode only though

Do you have suggestion on how to improve it?

**Comment by kaisalmen** [comment]
> All issues are related to asset management in node_modules in dev mode only though

Maybe there is a reason why they still rely on rollup for production 😆

**Pull request merged**
