### PR TITLE
Update to monaco 0.38/vscode 1.79

### PR DESCRIPTION
**Pull request by CGNonofr**
based https://github.com/CodinGame/monaco-vscode-api/pull/110

It was surprisingly easy!

So I fixed https://github.com/CodinGame/monaco-vscode-api/issues/108 in the same MR

### CODE REVIEW

**Comment by kaisalmen** [comment]
> What list are you talking about?

https://code.visualstudio.com/updates/v1_78
image  These are changes release with monaco-editor 0.38.0

> The main branch of vscode?

No rebase **update-monaco** branch on **main** branch in this repo.

**Comment by CGNonofr** [comment]
I'm still confused by the "It at least list the changes included there", what change was included here?

this branch is based on the other PR about views. I can try changing the order but I'm afraid of conflicts and I'm not sure about the point of it

**Comment by kaisalmen** [comment]
monaco-vscode-api is now combining vscode 1.78.0 with monaco-editor 0.37.1,
but the released vscode now seems to combine 1.78.0 with monaco-editor 0.38.0,
Hope this more clear now.

https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md
image

**Comment by kaisalmen** [comment]
I did a brute force rebase and squash test, but that did not work: https://github.com/CodinGame/monaco-vscode-api/tree/update-monaco-main

**Comment by CGNonofr** [comment]
Is it important for you to have the 0.38 fast?

**Comment by kaisalmen** [comment]
> Is it important for you to have the 0.38 fast?

People may come with questions, but let's not rush things.

**Comment by kaisalmen** [comment]
@CGNonofr did you forget to rebase this PR/branch on latest `view-services`. I won't be able to start reviewing it before Friday, I think. Is it ready? vscode 1.79.0 will not be available before June 2nd it seems.

**Comment by CGNonofr** [comment]
@kaisalmen I just forgot to push!

Yes I think it's ready! Friday is fine! Another PR related to views will come soon, I'd like to merge them all at once

**Comment by kaisalmen** [comment]
@CGNonofr testing this now. If looks good, I will approve.

**Review by kaisalmen — APPROVED** [review]
Tested. LGTM 🎉

**Pull request merged**
