### PR TITLE
Update to VSCode 1.90

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr I tested it locally and everything seems fine, but you broke the demo build

**Comment by kaisalmen** [comment]
I will give you a go once that is fixed.

**Comment by kaisalmen** [comment]
@CGNonofr I just read this in the VSCode release notes:
image

Does it mean you can/should move to node 20 here as well?

**Comment by CGNonofr** [comment]
> @CGNonofr I just read this in the VSCode release notes: image
> 
> Does it mean you can/should move to node 20 here as well?

AFAIK, They seem to be still using node 18 for building though, but I've switched to last versions and everything seems to work so... updated

**Comment by CGNonofr** [comment]
> > @CGNonofr I just read this in the VSCode release notes: image
> > Does it mean you can/should move to node 20 here as well?
> 
> AFAIK, They seem to be still using node 18 for building though, but I've switched to last versions and everything seems to work so... updated

Hum nop, doesn't work, rollbacked

**Review by kaisalmen — APPROVED** [review]
LGTM

**Comment by kaisalmen** [comment]
> Hum nop, doesn't work, rollbacked

ok, not aligning build and execution env sounds fishy. On the other hand the SW stack involved is deep and broad regarding dependencies.

**Pull request merged**
