### PR TITLE
VSCode 1.81/monaco 0.41

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by CGNonofr** [comment]
@kaisalmen 

image

**Comment by kaisalmen** [comment]
@CGNonofr of course, if you ask me like that. 😆 

Can you release a preview version?

**Comment by CGNonofr** [comment]
> @CGNonofr of course, if you ask me like that. laughing
> 
> Can you release a preview version?

I was planning to do it but stopped just before the npm publish... done as `@codingame/monaco-vscode-api@1.81.0-next.0`

**Review by kaisalmen — APPROVED** [review]
LGTM. Successfully tested with: https://github.com/TypeFox/monaco-languageclient/pull/520

**Pull request merged**
