### PR TITLE
Language detection worker

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by kaisalmen** [comment]
Is this ready for review? And if so, please release a next version!, too! 🙂

**Comment by CGNonofr** [comment]
> Is this ready for review? And if so, please release a next version!, too! slightly_smiling_face

Yes it is! :)

And as I said the currently published version if already based on it (just a few commits behind)

**Comment by kaisalmen** [comment]
> And as I said the currently published version if already based on it (just a few commits behind)

Ah, I see, languageDetectionWorker was already in there. Good, then I can already integrate that into `monaco-languageclient`.

**Comment by CGNonofr** [comment]
@kaisalmen will you have the time to look at it? at the end there is some fixes here I forgot about (terminals and audioCue are not working)

**Comment by kaisalmen** [comment]
Can you please publish a next release with all changes. Thank you.

**Comment by CGNonofr** [comment]
> Can you please publish a next release with all changes. Thank you.

sure, done as @codingame/monaco-vscode-api@1.80.1-next.0

**Review by kaisalmen — APPROVED** [review]
LGTM. Successfully tested with monaco-languageclient

**Pull request merged**
