### PR TITLE
Update to monaco 0.45

### LINKED ISSUE #289: Demo Page
Hi,

After the update, the Demo page appears incorrect.

### PR DESCRIPTION
**Pull request by CGNonofr**
published as 1.85.0-next.0

also fix #289

### CODE REVIEW

**Comment by CGNonofr** [comment]
I have the feeling someone didn't read the description (:

It looks like a great idea! Do you mind creating an issue or a discussion?

**Comment by kaisalmen** [comment]
> It looks like a great idea! Do you mind creating an issue or a discussion?

Will do...

**Comment by kaisalmen** [comment]
See: https://github.com/CodinGame/monaco-vscode-api/issues/291

**Comment by kaisalmen** [comment]
> You mean a next version? It's already done

Sorry, overlooked that.

**Comment by CompuIves** [comment]
I'll install this version on our codebase and see if everything works. I'll probably know by Monday!

**Comment by CompuIves** [comment]
But don't let me block the merge. If there's anything that need changing I can contribute them after as well.

**Comment by CGNonofr** [comment]
@kaisalmen => abae48aa4296bf8c24218b46038ddb5c379c23a6

**Comment by kaisalmen** [comment]
Latest finding form tests with preview version of https://github.com/TypeFox/monaco-languageclient/pull/584 `createConfiguredDiffEditor ` seems to be broken.

**Comment by CompuIves** [comment]
Upgrade was pretty smooth! Everything is working as expected here. The only hurdle was updating our xterm dependencies to `@xterm/xterm` and their respective versions. Other than that the upgrade went smoothly.

**Comment by CGNonofr** [comment]
> Latest finding form tests with preview version of [TypeFox/monaco-languageclient#584](https://github.com/TypeFox/monaco-languageclient/pull/584) `createConfiguredDiffEditor ` seems to be broken.

=> 576b10812945fa3e0e6d92ab00eb3fdaaa9e3271 (no idea why it wasn't an issue before nor the exact source of the issue, I've failed debugging it - there is a lot of events handlers and callbacks I was unable to follow - before I noticed that difference)

**Comment by kaisalmen** [comment]
@CGNonofr happy new year! 🎇 Thank you for finding this. With monaco-editor 0.44.0 they switched to a the new DiffEditor implementation, right.? Maybe this error is somehow related/follow-up problem (this is wild guessing, though).

If you release a new next version, I can verify it with our dependent library stack and then we can merge that in hopefully today.

**Comment by CGNonofr** [comment]
> @CGNonofr happy new year! 🎇 Thank you for finding this. With monaco-editor 0.44.0 they switched to a the new DiffEditor implementation, right.? Maybe this error is somehow related/follow-up problem (this is wild guessing, though).
> 
> If you release a new next version, I can verify it with our dependent library stack and then we can merge that in hopefully today.

Happy new year (:

You're probably right :shrug: 

published as 1.85.0-next.2 :)

**Review by kaisalmen — APPROVED** [review]
It looks good now. Did extensive testing with dependent repos/examples! LGTM

**Comment by CGNonofr** [comment]
> It looks good now. Did extensive testing with dependent repos/examples! LGTM

awesome! thanks for the time spent!

**Pull request merged**
