### PR TITLE
Few bugfixes

### LINKED ISSUE #68: Demo is broken with latest version (1.69.21)
Hi @CGNonofr 

I updated the demo (branch: https://github.com/CodinGame/monaco-vscode-api/tree/kaisalmen/demo-update) to the latest release and there is problem:
image

Switching to `1.69.20` it is still working. I see this error, though:
image

Are you aware of this already?

### PR DESCRIPTION
**Pull request by CGNonofr**
fixes #68

### CODE REVIEW

**Review by kaisalmen — DISMISSED** [review]
LGTM. Do you want to fix the GH Actions warning?

**Comment by CGNonofr** [comment]
> LGTM. Do you want to fix the GH Actions warning?

You mean the eslint warning? I challenge you do fix it!

**Comment by kaisalmen** [comment]
> You mean the eslint warning? I challenge you do fix it!

I see, what you mean, This is a false positive. What about 😎 

```javascript
// This is a false positive:
// eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
```

**Comment by CGNonofr** [comment]
> > You mean the eslint warning? I challenge you do fix it!
> 
> I see, what you mean, This is a false positive. What about sunglasses
> 
> ```js
> // This is a false positive:
> // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
> ```

Here we go b58ad203a94066f6acbb7588a5e6a53bc8cf8c7a + 541bfe85c088a5588b7341e1570bc3b00f222dc4

**Pull request merged**
