### PR TITLE
Update to VSCode 1.87

### PR DESCRIPTION
**Pull request by CGNonofr**
and some other fixes and improvements I've noticed while upgrading

### CODE REVIEW

**Review by kaisalmen — APPROVED** [review]
Works nicely locally. I will test the new release with monaco-languageclient once it is available.

**Comment by kaisalmen** [comment]
@CGNonofr independent of the example I always get this error with `3.0.0`:
image

**Comment by CGNonofr** [comment]
> @CGNonofr independent of the example I always get this error with `3.0.0`: image

It really looks like you have multiple versions of the extension service override



> @CGNonofr I also see that `hasUpdatedDefaultThemes` does not exist. This is related to trying to load original workers when using monaco-editor in classic mode (see #363): image

What you are trying seems a little hazardeous, let's talk about it on the linked issue

**Comment by kaisalmen** [comment]
> It really looks like you have multiple versions of the extension service override

I did not add anything and I just checked that `@codingame/monaco-vscode-extensions-service-override` is import nowhere.

**Comment by CGNonofr** [comment]
> > It really looks like you have multiple versions of the extension service override
> 
> I did not add anything and I just checked that `@codingame/monaco-vscode-extensions-service-override` is really imported nowhere.

You're right, found the issue!

**Pull request merged**
