### PR TITLE
Improve asset loading

### PR DESCRIPTION
**Pull request by CGNonofr**
fixes https://github.com/CodinGame/monaco-vscode-api/issues/90

### CODE REVIEW

**Review by kaisalmen — COMMENTED** [review]
I just performed the build locally and this looks awkward because each mp3 is there twice and the shorter once are not included somewhere:
image

**Comment by CGNonofr** [comment]
> I just performed the build locally and this looks awkward because each mp3 is there twice and the shorter once are not included somewhere: image

Well spotted, here's the fix: c2b56ce984e474f55ecd122d770d6c5dcad8d30a

**Comment by CGNonofr** [comment]
> Btw, are are these `??` checks still necessary? Did it change from 1.69 or are the `d.ts` incorrect here? image

Yes they are, the types says it's mandatory but it's treeshaken out of monaco
I don't know why it wasn't an issue before though...

=> d4bfc964c4d4de707e039146fbfe43a6d3d5b7ca

**Review by kaisalmen — APPROVED** [review]
Checked again ✅ Looking good now. LGTM 🎉

**Comment by CGNonofr** [comment]
@kaisalmen what about c3b40887e9ae39d602286385e930b2e469cad7e9 ?

**Review by kaisalmen — APPROVED** [review]
Checked once more. Let's go!

**Pull request merged**
