### PR TITLE
Improve view initialization

### PR DESCRIPTION
**Pull request by CGNonofr**
May be requires by #265 to be able to set the `Problems` view as default view

also includes forgotten working copy service override

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr will test this locally today.

**Comment by kaisalmen** [comment]
@CGNonofr the works as configured after I reset the user data. But that makes sense. 😊 

Where is the all the new views code coming from? You did not just write that, did you?

**Comment by CGNonofr** [comment]
> Where is the all the new views code coming from? You did not just write that, did you?

Nop! it comes from the VSCode layout service but I didn't find a way to not have to copy/paste it

**Comment by kaisalmen** [comment]
> Nop! it comes from the VSCode layout service but I didn't find a way to not have to copy/paste it

👍

**Review by kaisalmen — APPROVED** [review]
Works as expected after clearing user data.

**Pull request merged**
