### PR TITLE
Update to monaco 0.37

### PR DESCRIPTION
**Pull request by CGNonofr**
based on https://github.com/CodinGame/monaco-vscode-api/pull/93

### CODE REVIEW

**Comment by nihonium-cfx** [comment]
Would it be possible to expose more of notification service types within this update? Specifically, right now to properly implement custom notification service I need to extract some interfaces from `INotificationService` methods argument and return types, which works, but not ideal. Types I'd love to see reexported from `service-override/notifications.ts` are basically all exports from https://github.com/microsoft/vscode/blob/1.77.1/src/vs/platform/notification/common/notification.ts

**Review by kaisalmen — APPROVED** [review]
LGTM

**Comment by CGNonofr** [comment]
@kaisalmen I didn't test monaco-languageclient after the update to monaco 0.37, maybe it's worth it testing it before merging

**Comment by kaisalmen** [comment]
> test monaco-languageclient after the update to monaco 0.37

I am already on it. Just released the monaco-editor-workers support package as another prep step
Btw, I am using your wizardy in our monaco-editor-wrapper / and react component, but it is still WIP. It is almost a rewrite for v2!

**Pull request merged**
