### PR TITLE
Do not throw error from IEnvironmentVariableService

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Review by kaisalmen — APPROVED** [review]
LGTM. Just curious. What was the reason for using the annotations?

**Comment by CGNonofr** [comment]
> LGTM. Just curious. What was the reason for using the annotations?

I want the error message to contain the service name, do you have an alternative?

**Comment by kaisalmen** [comment]
No, I was first confused why there were some many lines changed.

**Comment by CGNonofr** [comment]
> No, I was first confused why there were some many lines changed.

In typescript, you can't have annotations on classes with expression is immediately used. I should probably have refactored it in another commit :thinking: sorry

**Pull request merged**
