### PR TITLE
Fixes and improvements

### LINKED ISSUE #198: Cannot use spaces in filename
There is a bug with how inputs in file explorer are handled. For example, on the demo page (https://codingame.github.io/monaco-vscode-api/) try to create a new file with name `hello world.txt`. You won't be able to because space doesn't work as expected. Furthermore `Cmd + A` to select all selects the folder group instead of the text inside input.

## Bug reproduction

https://github.com/CodinGame/monaco-vscode-api/assets/10388889/5a827f0e-4b54-45b0-8f35-480b2cd46143

## Actual VS code behavior

https://github.com/CodinGame/monaco-vscode-api/assets/10388889/a8adf8b4-872b-47a8-84e0-e1762ba772e5

### LINKED ISSUE #199: Regression in 1.82 command palette is broken
When you currently visit https://codingame.github.io/monaco-vscode-api/  and open the command palette and remove the ">" character it will throw the error as shown below. This in turn breaks quick file open functionality (registered in `registerFileSearchProvider`) which does not work anymore in this demo (nor in my own code).

**I think it is related, but any commands registered in `contributes.commands` via extension manifest also do not show up in the command palette anymore. Even if you have set keybindings, they will also not work.**

```error
index-9c7a3a1c.js:3 Uncaught Error: [createInstance] r_ depends on UNKNOWN service quickChatService.

Error: [createInstance] r_ depends on UNKNOWN service quickChatService.
    at J3._throwIfStrict (index-9c7a3a1c.js:714:4572)
    at J3._createInstance (index-9c7a3a1c.js:714:1121)
    at J3.createInstance (index-9c7a3a1c.js:714:914)
    at hwe.getOrInstantiateProvider (index-9c7a3a1c.js:702:6752)
    at kq.value (index-9c7a3a1c.js:702:6392)
    at D._deliver (index-9c7a3a1c.js:8:2987)
    at D._deliverQueue (index-9c7a3a1c.js:8:3078)
    at D.fire (index-9c7a3a1c.js:8:3504)
    at GD.doSetValue (index-9c7a3a1c.js:702:41619)
    at kq.value (index-9c7a3a1c.js:702:44454)
    at index-9c7a3a1c.js:3:12
(anonymous) @ index-9c7a3a1c.js:3
setTimeout (async)
Xft.unexpectedErrorHandler @ index-9c7a3a1c.js:1
onUnexpectedError @ index-9c7a3a1c.js:5
St @ index-9c7a3a1c.js:5
_deliver @ index-9c7a3a1c.js:8
_deliverQueue @ index-9c7a3a1c.js:8
fire @ index-9c7a3a1c.js:8
doSetValue @ index-9c7a3a1c.js:702
(anonymous) @ index-9c7a3a1c.js:702
_deliver @ index-9c7a3a1c.js:8
fire @ index-9c7a3a1c.js:8
onValueChange @ index-9c7a3a1c.js:214
(anonymous) @ index-9c7a3a1c.js:214

```

### PR DESCRIPTION
**Pull request by CGNonofr**
implements #190
fixes #198
fixes #199
workaround for #113

released as 1.82.4-next.1

### CODE REVIEW

**Review by kaisalmen — COMMENTED** [review]
@CGNonofr changes looks good, but I see one problem with `@codingame/monaco-editor-treemended`. If I import it as such:
```yaml
"monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.82.4-next.1 <1.83.0"
```
then it will conflict/be incompatible with the regular `monaco-editor` version (e.g. `0.43.0`) people have in their dependency tree.
Any idea how to solve this? Is it possible map the imported version to another one like we basically do it with the name?

**Comment by CGNonofr** [comment]
> @CGNonofr changes looks good, but I see one problem with `@codingame/monaco-editor-treemended`. If I import it as such:
> 
> ```yaml
> "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.82.4-next.1 <1.83.0"
> ```
> 
> then it will conflict/be incompatible with the regular `monaco-editor` version (e.g. `0.43.0`) people have in their dependency tree. Any idea how to solve this? Is it possible map the imported version to another one like we basically do it with the name?

What about using the npm `overrides` feature?

**Comment by kaisalmen** [comment]
> What about using the npm overrides feature?

Didn't know this one. Question is if this introduces more problem then it solves regarding treemending and yarn, pnpm, etc

**Review by kaisalmen — APPROVED** [review]
LGTM. My question regarding version conflicts does not block the approval.

**Comment by CGNonofr** [comment]
> > What about using the npm overrides feature?
> 
> Didn't know this one. Question is if this introduces more problem then it solves regarding treemending and yarn, pnpm, etc

That solution is not perfect either, but it's an alternative to the treemending. It's probably easier for pnpm

**Pull request merged**
