### PR TITLE
Fix encoding management

### PR DESCRIPTION
**Pull request by CGNonofr**
- Restore the usage of @vscode/iconv-lite-umd/jschardet to detect/handle different encoding (they are lazy-loaded)
- Remove some mocked file
- Attempt to move as much code as possible to the leaf packages: it allowed to remove almost 2mo from the main package

### CODE REVIEW

**Review by kaisalmen — CHANGES_REQUESTED** [review]
Local test look good and potentially smaller bundles are very welcome by end-users.
You introduced a new service and did not document it that's why I request changes.

**Comment by CGNonofr** [comment]
> Local test look good and potentially smaller bundles are very welcome by end-users. You introduced a new service and did not document it that's why I request changes.

Since it's an internal service override, I was wondering if it was worth it to document it 🤔

**Comment by kaisalmen** [comment]
> Since it's an internal service override, I was wondering if it was worth it to document it 🤔

Yes, that makes sense

**Review by kaisalmen — APPROVED** [review]
LGTM

**Comment by kaisalmen** [comment]
@CGNonofr Are more changes upcoming or is there another reason you did not merge this, yet?

**Comment by CGNonofr** [comment]
> @CGNonofr Are more changes upcoming or is there another reason you did not merge this, yet?

There are some... experiments, but if it leads to anything it'll be in another MR

**Comment by kaisalmen** [comment]
> We can release anytime if you want! I don't have anything else in the pipe though :)

We can combine it with other PR. No pressure from my side. I am busy with something else this week.

**Pull request merged**
