### PR TITLE
Various improvements and fixes

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr bloody hell I am sorry I forced push my changes (your status from yesterday). Can you re-push your status 🙈

**Comment by CGNonofr** [comment]
@kaisalmen I've added a bunch commits to better handle extension lifecycle by not reimplementing vscode logic: now the extension code is only loaded when the proper activationEvent is triggered, like in vscode (you can try it by hitting `Find all references` and see a new js is loaded)

**Comment by kaisalmen** [comment]
> like in vscode (you can try it by hitting Find all references and see a new js is loaded)

Confirmed. `monaco-languageclient` looks good, too.

**Review by kaisalmen — APPROVED** [review]
LGTM 🎉

**Comment by CGNonofr** [comment]
> It is now approved or are there more changes incoming?

I noticed some issues while integrating it ; I guess I'll find some others but I'll create others PRs, let's merge it

**Comment by kaisalmen** [comment]
> I noticed some issues while integrating it ; I guess I'll find some others but I'll create others PRs, let's merge it

But this does not block next `monaco-languageclient` release or does it?

**Comment by CGNonofr** [comment]
There is no more known issues. This PR includes vital fixes for monaco-languageclient

**Pull request merged**
