### PR TITLE
Audio cue service override

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by CGNonofr** [comment]
> @CGNonofr The audio cue is working, but I see these errors in the demo (related to the latest onig wasm textmate changes, I guess):
> 
> image

Sorry, it was a rebase issue, fix amended

**Review by kaisalmen — APPROVED** [review]
Tested succesfully now. LGTM 🎉

**Comment by CGNonofr** [comment]
Thanks, you rocks!

brace yourself, more is coming

**Comment by kaisalmen** [comment]
@CGNonofr any idea why there is no `1.76.1`? Aren't new versions automatically released?

**Comment by CGNonofr** [comment]
> @CGNonofr any idea why there is no `1.76.1`? Aren't new versions automatically released?

The publish process failed silently...

**Pull request merged**
