### PR TITLE
View services

### PR DESCRIPTION
**Pull request by CGNonofr**
based on https://github.com/CodinGame/monaco-vscode-api/pull/109

it includes:
- a way to run the extension code (required for the references-view default extension)
- file explorer
- debug components
- TypeHierarchy/CallHierarchy/References
- a way to register a custom View

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr FYI build breaks locally with the same error you see in the GHA build.

**Comment by CGNonofr** [comment]
> @CGNonofr FYI build breaks locally with the same error you see in the GHA build.

fixed in 65fd3df4b1d4f958818e9316ff8f36ea6e2a40a5

**Comment by kaisalmen** [comment]
> fixed in https://github.com/CodinGame/monaco-vscode-api/commit/65fd3df4b1d4f958818e9316ff8f36ea6e2a40a5

Testing this now....

**Comment by kaisalmen** [comment]
I have tested the changes and the expanded demo is nice. I will look more closely at the changes next week.

**Comment by CGNonofr** [comment]
> @CGNonofr can you release a preview / next version of this for playing around?

Done!

**Comment by kaisalmen** [comment]
@CGNonofr have you seen this error during `npm install` before`?
image

**Comment by CGNonofr** [comment]
> @CGNonofr have you seen this error during `npm install` before? It continues... image

Never in my life! I don't even know why git is involved here

**Comment by kaisalmen** [comment]
I reset the repo before starting. Happens during long running `yarn install --ignore-engines`

**Review by kaisalmen — APPROVED** [review]
Let's go!

**Comment by kaisalmen** [comment]
> Never in my life! I don't even know why git is involved here

Happens in the pipeline, too:
https://github.com/CodinGame/monaco-vscode-api/actions/runs/5121351480/jobs/9209003566

**Comment by CGNonofr** [comment]
> > Never in my life! I don't even know why git is involved here
> 
> Happens in the pipeline, too: https://github.com/CodinGame/monaco-vscode-api/actions/runs/5121351480/jobs/9209003566

Oh right, it's not blocking! we're building vscode extensions here, maybe some of those we don't use don't build properly

**Pull request merged**
