### PR TITLE
Use official runners

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by CGNonofr** [comment]
@kaisalmen you were right, it works on official github runners...

**Review by kaisalmen — APPROVED** [review]
LGTM. Why are these eslint settings no longer required?

**Comment by CGNonofr** [comment]
> LGTM. Why are these eslint settings no longer required?

There is an extends and those configs are already in the extended config

**Comment by kaisalmen** [comment]
> There is an extends and those configs are already in the extended config

Yes, thanks, just checked in parallel. That is all defined in `@codingame/eslint-config`

**Pull request merged**
