### PR TITLE
Cleanup and add missing service overrides

### PR DESCRIPTION
**Pull request by CGNonofr**
I don't think there is any relevant service override left to implement :)

### CODE REVIEW

**Comment by kaisalmen** [comment]
@CGNonofr 🍾 I still need to test it

**Review by kaisalmen — APPROVED** [review]
Looking good! Next is update to vite 5 / rollup 4? 🤯

**Comment by CGNonofr** [comment]
> Looking good! Next is update to vite 5 / rollup 4? 🤯

We are already using rollup 4, don't we?

**Comment by kaisalmen** [comment]
> We are already using rollup 4, don't we?

Oh yes, nevermind! 😊 Then switching to vite 5 should be easy

**Comment by CGNonofr** [comment]
> > We are already using rollup 4, don't we?
> 
> Oh yes, nevermind! 😊 Then switching to vite 5 should be easy

I've already tried, there is a weird error about experimental decorator that looks blocking but is not (but still ugly). I was hoping them to fix it but it doesn't seem there is any change since then

**Pull request merged**
