### PR TITLE
Fix main dependencies

### PR DESCRIPTION
**Pull request by CGNonofr**
fix https://github.com/CodinGame/monaco-vscode-api/discussions/518

### CODE REVIEW

**Review by kaisalmen — APPROVED** [review]
LGTM

**Comment by Nuthin2do** [comment]
The xterm.js appears again in the output folder with the 11.1.0 version

**Comment by CGNonofr** [comment]
> The xterm.js appears again in the output folder with the 11.1.0 version

Are you sure? => https://www.npmjs.com/package/@codingame/monaco-vscode-api?activeTab=code there is no xterm

**Comment by Nuthin2do** [comment]
Pretty sure :-). This is my package.json:

"scripts": {
    "dev": "vite --config vite.config.ts",
    "dev:build": "vite build --watch --mode development",
    "build": "vite --config vite.config.ts build --base=./ --emptyOutDir"
  },
"devDependencies": {
    "@codingame/esbuild-import-meta-url-plugin": "^1.0.2",
    "@types/node": "^22.9.0",
    "@types/vscode": "^1.95.0",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3",
    "vite": "^5.4.11"
  },
  "dependencies": {
    "@codingame/monaco-vscode-configuration-service-override": "^11.1.0",
    "@codingame/monaco-vscode-debug-service-override": "^11.1.0",
    "@codingame/monaco-vscode-extensions-service-override": "^11.1.0",
    "@codingame/monaco-vscode-files-service-override": "^11.1.0",
    "@codingame/monaco-vscode-javascript-default-extension": "^11.1.0",
    "@codingame/monaco-vscode-language-detection-worker-service-override": "^11.1.0",
    "@codingame/monaco-vscode-languages-service-override": "^11.1.0",
    "@codingame/monaco-vscode-model-service-override": "^11.1.0",
    "@codingame/monaco-vscode-standalone-typescript-language-features": "^11.1.0",
    "@codingame/monaco-vscode-textmate-service-override": "^11.1.0",
    "@codingame/monaco-vscode-theme-defaults-default-extension": "^11.1.0",
    "@codingame/monaco-vscode-theme-service-override": "^11.1.0",
    "@codingame/monaco-vscode-typescript-basics-default-extension": "^11.1.0",
    "@codingame/monaco-vscode-typescript-language-features-default-extension": "^11.1.0",
    "monaco-editor": "npm:@codingame/monaco-vscode-editor-api@^11.1.0",
    "vscode": "npm:@codingame/monaco-vscode-api@^11.1.0"
  },
  
  and this is how the output looks like:
  
image

And it appears every time even if i delete the output folder let vite create it

**Comment by CGNonofr** [comment]
then please run `npm list @xterm/xterm`

**Comment by CGNonofr** [comment]
Ok I think I understand, it's not pulled by the main but by the extensions service override, which is a default one

**Comment by Nuthin2do** [comment]
> but by the extensions service override

Yes, it seems so, because this is the ouput of `npm list @xterm/xterm` :

image

**Comment by Nuthin2do** [comment]
Don't want to be the bearer of bad news, but now i get an error when try to build solution:

`x Build failed in 13.97s
error during build:
[vite]: Rollup failed to resolve import "@codingame/monaco-vscode-chat-extensions-notebook-task-terminal-testing-common/vscode/vs/workbench/contrib/terminal/common/terminal" from "C:/temp/NewEditor/node_modules/vscode/vscode/src/vs/workbench/contrib/terminal/common/terminalContextKey.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/temp/NewEditor/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65589:17)
    at onRollupWarning (file:///C:/temp/NewEditor/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65621:5)
    at onwarn (file:///C:/temp/NewEditor/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65284:7)
    at file:///C:/temp/NewEditor/node_modules/rollup/dist/es/shared/node-entry.js:19409:13
    at Object.logger [as onLog] (file:///C:/temp/NewEditor/node_modules/rollup/dist/es/shared/node-entry.js:21135:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/temp/NewEditor/node_modules/rollup/dist/es/shared/node-entry.js:20024:26)
    at file:///C:/temp/NewEditor/node_modules/rollup/dist/es/shared/node-entry.js:19982:26`

Do i have to explicitly externalize the package as vite suggests?

Thank you very much for your efforts.

**Comment by CGNonofr** [comment]
Hum that's no good news!

**Pull request merged**
