### PR TITLE
segmenter fallback

### PR DESCRIPTION
**Pull request by BusinessDuck**
Working on fix https://github.com/CodinGame/monaco-vscode-api/issues/397

### CODE REVIEW

**Comment by CGNonofr** [comment]
Can you please implement it as a commit/patch instead? that way it would be simpler to synchronize with the microsoft team

refer to https://github.com/CodinGame/monaco-vscode-api/blob/main/docs/vscode_monaco_upgrade.md on how to do it

**Comment by BusinessDuck** [comment]
Sure, let me a few minutes

**Comment by BusinessDuck** [comment]
I can try later

**Comment by BusinessDuck** [comment]
I am done with patch style

**Comment by CGNonofr** [comment]
Did you open a PR on the VSCode side?

btw, can you please cleanup the PR? (remove rollbacked commits) ?

**Comment by BusinessDuck** [comment]
> Did you open a PR on the VSCode side?

Not yet

> btw, can you please cleanup the PR? (remove rollbacked commits) ?

Done

**Comment by CGNonofr** [comment]
> > Did you open a PR on the VSCode side?
> 
> Not yet

Please do, I'd like the microsoft team opinion on it before backporting it

**Comment by BusinessDuck** [comment]
https://github.com/microsoft/vscode/issues/210577

**Comment by CGNonofr** [comment]
I've make a change to remove the footer from the patches so that all of them don't change depending on the git version, can you please rebase and use the updated command?

**Comment by BusinessDuck** [comment]
PR has been Updated

**Comment by BusinessDuck** [comment]
Workflow fixed

**Comment by BusinessDuck** [comment]
can you run workflow?

**Comment by BusinessDuck** [comment]
can we temprorary merge that MR until vscode team is in progress with it? Lets create an issue to drop that patch after vscode team decision

**Comment by CGNonofr** [comment]
@kaisalmen @CompuIves What are you opinion on that? I'm really not sure to understand the problem enough to make a decision

**Comment by kaisalmen** [comment]
@CGNonofr I was busy with other things last week and likely this week as well. Without digging into it I can't provide qualified input here.

**Comment by CGNonofr** [comment]
If you rebase on main, I can release a pre-release version just for you if you want

**Comment by CGNonofr** [comment]
🚀 Deployed on https://66432e5b8187c0c7bbac77f9--monaco-vscode-api.netlify.app

**Comment by CGNonofr** [comment]
deployed as [5.1.2-segmenter.1](https://www.npmjs.com/package/@codingame/monaco-vscode-api/v/5.1.2-segmenter.1)

**Comment by BusinessDuck** [comment]
I did some test on my side of the project everything looks good. TypeScript with `es2020.intl` library not cause a problems anymore.

Do you cough something on demo stand? I also check it and don't see any problems, we need to change to chinese locale to check it

**Comment by CGNonofr** [comment]
I don't think it'll be merged into main until some feedback from the microsoft team

**Pull request closed without merging**
