### PR TITLE
fix: build for darwin

### PR DESCRIPTION
**Pull request by dlvhdr**

### CODE REVIEW

**Comment by dlvhdr** [comment]
@CGNonofr I'm not sure if the `sed` command works like this in linux.
Regarding `rsync` I pretty sure linux has it installed.

**Comment by CGNonofr** [comment]
Thanks! actually, you can even remove the sed and it's not useful anymore!

**Comment by dlvhdr** [comment]
@CGNonofr Done!

**Comment by CGNonofr** [comment]
I fixed the github action trigger, can you please rebase on main to check the build in the github action?

**Comment by CGNonofr** [comment]
Ok it seems to work! One last thing, can you please follow the [conventionnal commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) convention?

**Comment by CGNonofr** [comment]
> Something like this? Not sure if I followed it correctly

Perfect! I would have probably labelled the sed removal by a `clean` instead of a `fix` but it's no big deal

**Review by CGNonofr — APPROVED** [review]

**Pull request merged**
