### PR TITLE
Improve patch management

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Comment by CGNonofr** [comment]
@kaisalmen I'd really like to know what you think about this change regarding patches, do you think it's enough?

**Comment by kaisalmen** [comment]
> what you think about this change regarding patches, do you think it's enough?

It is clearer what is happening. Was there a specific motivation for changing it?

**Review by kaisalmen — APPROVED** [review]
LGTM. Makes what is happening a bit clearer.

**Comment by CGNonofr** [comment]
> > what you think about this change regarding patches, do you think it's enough?
> 
> It is clearer what is happening. Was there a specific motivation for changing it?

I wanted to improve it for a long time, there are more and more stuff on the patch and having everything mixed up in a big patch make it hard to maintain and to know why a specific change was made

**Comment by kaisalmen** [comment]
Will you trigger a new release once #365 and #366 are merged?

**Comment by CGNonofr** [comment]
> Will you trigger a new release once #365 and #366 are merged?

Sure ! Already running !

**Comment by CompuIves** [comment]
I love this change!

**Pull request merged**
