### PR TITLE
Timeline view

### PR DESCRIPTION
**Pull request by CGNonofr**

### CODE REVIEW

**Review by kaisalmen — DISMISSED** [review]
LGTM. Tested locally.
Note: The `package-lock.json` is changed again when I do `npm i` in the demo. I use volta and it uses the correct npm version you specify. I don't know what is going on.

**Comment by CGNonofr** [comment]
> LGTM. Tested locally. Note: The `package-lock.json` is changed again when I do `npm i` in the demo. I use volta and it uses the correct npm version you specify. I don't know what is going on.

Ok I've understood... to have a clean package-lock, I remove the package-lock and node_modules then run `npm i`. And it seems running `npm i` a second time does change the package-lock (by adding the `name` field on every local dependencies)

fixed in last 2 commits

**Comment by kaisalmen** [comment]
@CGNonofr do you want to go the non-LTS version on purpose?

**Comment by CGNonofr** [comment]
> @CGNonofr do you want to go the non-LTS node version on purpose? 20 is LTS 21 is current

No really, is that a big deal? just trying to be as up to date as possible

**Review by kaisalmen — APPROVED** [review]
LGTM

**Comment by kaisalmen** [comment]
@CGNonofr is there no more automatic release?

**Comment by kaisalmen** [comment]
When are you planning to publish the next one. I want to release a new `monaco-languageclient` version later this week.

**Pull request merged**
