### PR TITLE
Update to VSCode 1.92

### PR DESCRIPTION
**Pull request by CGNonofr**
Also microsoft did change a lot how language packages work, allowing us to removing a lot of code and be way closer to how it works in VSCode itself by using the same bundled format (which is lighter because it contains only indexes instead of string keys)

### CODE REVIEW

**Review by kaisalmen — APPROVED** [review]
Thank you. LGTM. I will test and integrate the new release with monaco-languageclient and its examples.

**Comment by CGNonofr** [comment]
@kaisalmen forgot to make it as a breaking change :(

**Comment by kaisalmen** [comment]
@CGNonofr can you re-release it as 8.0.0?

**Comment by CGNonofr** [comment]
> @CGNonofr can you re-release it as 8.0.0?

done!

**Pull request merged**
