### PR TITLE
WebWorker extension host

### PR DESCRIPTION
**Pull request by CGNonofr**
Allows to run extension code in a worker or not

based on https://github.com/CodinGame/monaco-vscode-api/pull/146

known issues:
- [x] error with webview: No service worker controller found. Waiting for controllerchange. (markdown not working properly)
- [x] find a way to make vite ignore the tsserver.web.js dynamic import
- [ ] Workers and fetch don't work in localExtHost (url are not transformed)

### CODE REVIEW

**Comment by digitallyserviced** [comment]
damn dude, amazing work!



 Also so you can perf on this... very snappy

Screenshot_2023-07-21-13-20-11_3520x1080

Is this something I am doing wrong? or relating to your known issue? Because the `[vite] warning` isnt much of an issue lol... 

```
   Error: No Project.
        at Object.ThrowNoProject (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:170521:17)
        at _ProjectService.doEnsureDefaultProjectForFile (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:174519:195)
        at _ProjectService.ensureDefaultProjectForFile (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:174514:81)
        at WorkerSession.getFileAndProjectWorker (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:179533:83)
        at WorkerSession.getFileAndProject (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:179519:23)
        at WorkerSession.provideCallHierarchyIncomingCalls (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:180420:42)
        at provideCallHierarchyIncomingCalls (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:178418:49)
        at http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:180470:75
        at WorkerSession.executeWithRequestId (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:180462:20)
        at WorkerSession.executeCommand (http://127.0.0.1:5174/@fs//home/chris/Documents/monaco-vscode-api/dist/assets/tsserver.web.js:180470:35)
```

**Comment by kaisalmen** [comment]
@CGNonofr this is not really ready for review, is it? Do you want to convert it to a draft PR for now?

I quickly looked over the commits. I was wondering if you plan to bring the vscode patches to the real code base?

Is it possible you please release a next version, so I can test it more easily with `monaco-languageclient`? Or does it make more sense to port back the changes that break `monaco-languageclient` build to #146 and release a new next build based on that?

**Comment by CGNonofr** [comment]
> > this is not really ready for review, is it? Do you want to convert it to a draft PR for now?
> 
> Yep, I forgot about that feature :)
> 
> > I quickly looked over the commits. I was wondering if you plan to bring the vscode patches to the real code base?
> 
> Some commits can be included in the vscode codebase, I already did previously to reduce the patch size. Some others are really specific with the way we use the code here
> 
> > Is it possible you please release a next version, so I can test it more easily with monaco-languageclient? Or does it make more sense to port back the changes that break monaco-languageclient build to #146 and release a new next build based on that?
> 
> I not really happy with a few thing here, it still requires some work. Unfortunately the previous PR has an issue I didn't bother to fix because I know this PR will do it. I can still release a next version though so you can start playing with it

**Comment by CGNonofr** [comment]
@kaisalmen @codingame/monaco-vscode-api@1.80.0-next.4 published

**Comment by kaisalmen** [comment]
@CGNonofr thank you. I can make `monaco-languageclient` compile again. Can you explain me how to do `registerExtensionFile` or what to do now (e.g. register grammar or language config)? The function is no longer available and `registerFileUrl` does work as expected (see https://github.com/TypeFox/monaco-languageclient/tree/monaco-0.40).

**Comment by CGNonofr** [comment]
> @CGNonofr thank you. I can make `monaco-languageclient` compile again. Can you explain me how to do `registerExtensionFile` or what to do now (e.g. register grammar or language config)? The function is no longer available and `registerFileUrl` does work as expected (see https://github.com/TypeFox/monaco-languageclient/tree/monaco-0.40).

You seem to have done it right. There was complex logic because some files are used via the fileService and some are just transformed into url and put in some css or html files (and we can't generate an url from a file content asynchronously, or I didn't find a way). The sync/async file logic was to complex and I discovered the `new URL(..., import.meta.url)` syntax which is supported by at least rollup/vite/webpack so I decided we don't need anything else than an extension file uri registration and it simplifies everything. What do you think?

**Comment by kaisalmen** [comment]
@CGNonofr It crashes before reaching service init (I force pushed my latest service additions):
image

**Comment by kaisalmen** [comment]
@CGNonofr And there is a wrong import in the code I fixed locally for now:
image

**Comment by CGNonofr** [comment]
> @CGNonofr It crashes before reaching service init (I force pushed my latest service additions on the bespoke branch): image

Are you testing the version I've published? registerStaticBrowserUri is a new method introduced in the treemending patch.

No idea about the other issue, maybe they are related?

> @CGNonofr And there is a wrong import in the code I fixed locally for now: image

Ok rollup renames to files unproperly, will check

**Comment by kaisalmen** [comment]
> Regarding the second one, it's due to the vite watch mode a little dump with import.meta.url (no issue in prod mode which uses rollup). I found a workaround though:

Thanks, that works.

**Comment by kaisalmen** [comment]
@CGNonofr I needed to add extensions service (was not required with 1.79) and this one requires output service (the logger actually). Was that desired or may this be an effect of the other problem above?

**Comment by CGNonofr** [comment]
> @CGNonofr I needed to add extensions service (was not required with 1.79) 

The extension service is supposed to be automatically added along with layout and environment, that's weird!

> and this one requires output service (the logger actually).

Didn't test removing other service override yet, will add it as dependency :+1:

> Was that desired or may this be an effect of the other problem above?

It is not, the only expected breaking change if the replacement of `registerExtensionFile` to `registerExtensionFileUri`

**Comment by CGNonofr** [comment]
@kaisalmen I'm now happy with the result, I think it's reviewable :)

**Comment by CompuIves** [comment]
Holy cow, this is amazing!!! I'm very excited for this, thanks for the work on this @CGNonofr!!

**Comment by kaisalmen** [comment]
> @kaisalmen I'm now happy with the result, I think it's reviewable/testable :)

Awesome. I found an issue with `monaco-languageclient`, please see https://github.com/TypeFox/monaco-languageclient/tree/monaco-0.40.
Can you update the list of services that are provided? Thank you.

I have skimmed over the changes. Are you aware you can use the regular `new Worker(...)` syntax with with vite instead of the `xyz?Worker` notation? They actually advise not to use the `?` notation.

**Comment by CGNonofr** [comment]
> > @kaisalmen I'm now happy with the result, I think it's reviewable/testable :)
> 
> Awesome. I found an issue with `monaco-languageclient`, please see https://github.com/TypeFox/monaco-languageclient/tree/monaco-0.40. Can you update the list of services that are provided in the README? Thank you.

I will!

> I have skimmed over the changes. Are you aware you can use the regular `new Worker(...)` syntax with with vite instead of the `xyz?Worker` notation? They actually advise not to use the `?` notation.

Do I?

**Comment by kaisalmen** [comment]
> Do I?

Sorry, maybe that was a bit too short / misleading. Was wondering if instead of using:
```typescipt
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker.js?worker'
```

```typescipt
new Worker(scriptUrl, options)
```
This way you can control the worker options without relying on vite. I don't know if that makes things better or worse, though.

Honestly, your work is awesome, but reviewing it properly is kind of hard. This currently is more like, I see if the "dev" branch works in `monaco-languageclient` and I can expose the stuff properly to depending projects. 🙈

**Comment by CGNonofr** [comment]
> > Do I?
> 
> Sorry, maybe that was a bit too short / misleading. Was wondering if instead of using:
> 
> ```
> import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker.js?worker'
> ```
> 
> ```
> new Worker(scriptUrl, options)
> ```
> 
> This way you can control the worker options without relying on vite. I don't know if that makes things better or worse, though.

I'm not sure what you mean here. On watch mode, vite use module workers, not on build mode so we need to let vite decide the worker option. That was a big source of problem and I needed some hacks to make it work

> 
> Honestly, your work is awesome, but reviewing it properly is kind of hard. This currently is more like, I see if the "dev" branch works in `monaco-languageclient` and I can expose the stuff properly to depending projects. see_no_evil

I completely agree. I've spent hours and hours to understand and refactor things, I don't really expect you to be able to fully review it. I mainly expect you to notice obvious mistakes and test it (another way than I did)

**Comment by CGNonofr** [comment]
@kaisalmen can you give a look at the `@codingame/monaco-vscode-api@1.80.0-next.6`?

**Comment by kaisalmen** [comment]
> can you give a look at the @codingame/monaco-vscode-api@1.80.0-next.6?

@CGNonofr looking good. I just pushed an update to the monaco-0.40 branch. Tested it locally without problem. Build is green now, too.

**Review by kaisalmen — APPROVED** [review]
Based on the tested performed with `monaco-languageclient` this is good to go. LGTM.

**Comment by kaisalmen** [comment]
Let's make this the baseline (merge back or FF main) and iterate from there. Sounds good?

**Comment by CGNonofr** [comment]
Fyi, the published version is built from the next PR, but it's not expected to fix anything, just adding a service

**Comment by kaisalmen** [comment]
> Fyi, the published version is built from the next PR, but it's not expected to fix anything, just adding a service

No problem. My plan is anyway to wait for #152 before releasing any final version of `monaco-languageclient`. I will likely release a next version as well to iterate the dependent repos/libs.

**Comment by kaisalmen** [comment]
Wonderful 1.80.0 is available!🎉

**Pull request merged**
