### PR TITLE
Make extension service optional

### PR DESCRIPTION
**Pull request by CGNonofr**
@kaisalmen it will require to add it back in monaco-languageclient

### CODE REVIEW

**Comment by CGNonofr** [comment]
> @CGNonofr ok, can you tell me why you need to do this?

This library can be used for other things than using VSCode extensions, I just try to make the library as modular as possible

Do you think it's a bad idea?

**Comment by CGNonofr** [comment]
> > This library can be used for other things than using VSCode extensions, I just try to make the library as modular as possible
> 
> Interesting. Do you have an example?
> 
> > Do you think it's a bad idea?
> 
> No, just want to understand the motivation 🙂

You can use the configuration/keybindings/view service override without needing anything else. It doesn't correspond to any use-case I'll have but better keep the library as modular as possible

**Comment by kaisalmen** [comment]
@CGNonofr didn't you put the `fileService` there by intention in the past. Was that necessity removed after recent changes? Just want to prevent potential regressions.
Can you release a next version for testing once you are done with the changes? Thanks

**Comment by CGNonofr** [comment]
> @CGNonofr didn't you put the `fileService` there by intention in the past. Was that necessity removed after recent changes? Just want to prevent potential regressions. Can you release a next version for testing once you are done with the changes? Thanks

Ok you made me change my mind :)

**Pull request closed without merging**
